image:
  registry: "docker.io"
  repository: "apache/kafka"
  tag: "4.1.1"

kafka:
  clusterId: "MkU3OEVBNTcwNTJENDM2Qk"
  storage:
    size: 20Gi
    className: "standard"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

ui:
  enabled: true
  image: provectuslabs/kafka-ui:latest